<a href="https://colab.research.google.com/github/AnupRawka/pytorch-tutorial/blob/main/exercises/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch
t = torch.rand(7,7)
t
# Create random tensor


tensor([[0.2975, 0.4737, 0.5974, 0.2864, 0.4750, 0.7577, 0.5261],
        [0.9159, 0.8459, 0.6625, 0.7263, 0.9865, 0.0116, 0.4462],
        [0.2101, 0.4653, 0.7427, 0.6749, 0.5051, 0.3465, 0.9306],
        [0.1483, 0.4905, 0.8100, 0.6947, 0.1705, 0.7659, 0.5346],
        [0.1557, 0.4656, 0.5126, 0.3618, 0.3913, 0.1340, 0.9994],
        [0.0435, 0.4382, 0.8562, 0.9396, 0.5525, 0.2426, 0.6790],
        [0.0019, 0.3672, 0.7059, 0.4307, 0.3755, 0.9825, 0.1511]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
t_17 = torch.rand(1,7)
t_17
# Perform matrix multiplication
torch.matmul(t, t_17.T)

tensor([[1.8382],
        [2.0685],
        [2.0469],
        [1.9748],
        [1.5523],
        [2.0272],
        [1.7844]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [11]:
# Set manual seed
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)

# Create two random tensors
t = torch.rand(7,7)
t2 = torch.rand(1,7)

# Matrix multiply tensors
z = torch.matmul(t, t2.T)
z, z.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [14]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [18]:
# Set random seed
# torch.cuda.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()
# Create two random tensors on GPU
tx = torch.rand(size=(2, 3)).to('cuda')
ty = torch.rand(size=(2, 3)).to('cuda')
tx, ty


(tensor([[0.9351, 0.9412, 0.5995],
         [0.0652, 0.5460, 0.1872]], device='cuda:0'),
 tensor([[0.0340, 0.9442, 0.8802],
         [0.0012, 0.5936, 0.4158]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [20]:
# Perform matmul on tensor_A and tensor_B
z = torch.matmul(tx, ty.T)
z, z.shape

(tensor([[1.4482, 0.8091],
         [0.6825, 0.4020]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
torch.max(z)
# Find min
torch.min(z)

tensor(1.4482, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [27]:
# Find arg max
z.argmax(), z.argmin()

# Find arg min


(tensor(0, device='cuda:0'), tensor(3, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [28]:
torch.manual_seed(7)

# Create random tensor
tensor_D = torch.rand(size=(1, 1, 1, 10))

# Remove single dimensions
tensor_E = tensor_D.squeeze()

# Print out tensors
print(tensor_D, tensor_D.shape)
print(tensor_E, tensor_E.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
